---
abstract: 'convert Win32 status strings to integers and back'
author:
  - 'Rohan McGovern <rohan@mcgovern.id.au>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-Status
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Readonly: 0
  Test::More: 0
version: 0.81
